// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2019DeepSpace.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc5053.FRC2019DeepSpace.subsystems.*;

/**
 *
 */
public class clawOpenAndEjectCargo extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public clawOpenAndEjectCargo() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
        addSequential(new clawOperationTimedOpen(0));
        addSequential(new clawPunch(0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    /**********************
     * Each time the JAVA is generated from robot builder, the automatically generated
     * code does not include the parameters.
     * 
     * After JAVA is generated from robot builder, comment out the addSequential 
     * commands in the AUTOGENERATED CODE ABOVE.
     ***********************/
    addSequential(new clawOperationTimedOpen(0.3));
    /***********************
     * 20190218
     * Increase the timer from 0.2 seconds to 3 seconds
     * This should help us score even if the claw is slow to open
     */
    addSequential(new clawPunch(3));  
} 
}
