// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2019DeepSpace.commands;
import org.usfirst.frc5053.FRC2019DeepSpace.OI;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


import org.usfirst.frc5053.FRC2019DeepSpace.Robot;

/**
 *
 */
public class driveTrainArcadeTeleOp extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public driveTrainArcadeTeleOp() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // NOTE:  Axis 0 : Left x-axis
        //        Axis 1 : Left y-axis
        //        Axis 4 : Right x-axis
        //        Axis 5 : Right y-axis
        //
        // 20190205 Modified the rotate stick to feed a negative value -- the
        //          direction of the physical turn was reverse of our
        //          desired direction
        
        SmartDashboard.putNumber("x", Robot.oi.xbox360.getRawAxis(1));
        // double max_forward_power = 1.00;
        double max_forward_power = OI.MAX_DRIVE_POWER;
        double min_forward_power = 0.25;
        double deadband = 0.01;

        double slope = max_forward_power - min_forward_power;

        double forwardPowerValue = 0;
        if ((Robot.oi.xbox360.getRawAxis(1) <= deadband) && 
            (Robot.oi.xbox360.getRawAxis(1) >= -deadband))
        {
            forwardPowerValue = 0;
        }
        else if (Robot.oi.xbox360.getRawAxis(1) < 0)
        {
            forwardPowerValue = (slope * Robot.oi.xbox360.getRawAxis(1)) - min_forward_power;
        }
        else if (Robot.oi.xbox360.getRawAxis(1) > 0)
        {
            forwardPowerValue = (slope * Robot.oi.xbox360.getRawAxis(1)) + min_forward_power;
        }

        double rotationpower = 0;
        if ((Robot.oi.xbox360.getRawAxis(4) <= deadband) &&
            (Robot.oi.xbox360.getRawAxis(4) >= -deadband))
        {
            rotationpower = 0;
        }
        else if (Robot.oi.xbox360.getRawAxis(4) < 0)
        {
            rotationpower = (slope * Robot.oi.xbox360.getRawAxis(4)) - min_forward_power;
        }
        else if (Robot.oi.xbox360.getRawAxis(4) > 0)
        {
            rotationpower = (slope * Robot.oi.xbox360.getRawAxis(4)) + min_forward_power;
        }
        SmartDashboard.putNumber("JoyStick Y-Axis", Robot.oi.xbox360.getRawAxis(1));
        SmartDashboard.putNumber("forwardPowerValue", forwardPowerValue);
        SmartDashboard.putNumber("Joystick X-Axis", Robot.oi.xbox360.getRawAxis(4));
        SmartDashboard.putNumber("rotatePowerValue", rotationpower);

       //Robot.driveTrain.arcade(Robot.oi.xbox360.getRawAxis(1)*.8,
                               //-Robot.oi.xbox360.getRawAxis(4)*.8);  
                                Robot.driveTrain.arcade(forwardPowerValue,
                                
                                -rotationpower);               
        //Robot.driveTrain.arcade(Robot.oi.xbox360.getRawAxis(1)+0.15,
        //                        -(Robot.oi.xbox360.getRawAxis(4)+0.15));             
    
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveTrain.stop(); // 20190208
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();  // 20190208
    }

    

    

}
